name: Development

on:
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Read VERSION file
        id: read_version
        run: |
          version=$(cat VERSION)
          echo "version=$version" >> $GITHUB_OUTPUT

  build:
    needs: checkout
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ format('{0} - NTSYNC', needs.checkout.outputs.version) }}
