name: Development

on:
  workflow_dispatch:

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      tag_abbrev: ${{ steps.version.outputs.tag_abbrev }}
      tag_offset: ${{ steps.version.outputs.tag_offset }}
      sha_short: ${{ steps.version.outputs.sha_short }}
      full_desc: ${{ steps.version.outputs.full_desc }}
      branch: ${{ steps.version.outputs.branch }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

  build:
    needs: version
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ needs.version.outputs.full_desc }}-${{ needs.version.outputs.branch }}


