name: Development

on:
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read_version.outputs.version }}
      commitid: ${{ steps.commit.outputs.sha_short }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Read VERSION file
        id: read_version
        run: |
          version=$(cat VERSION)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get short commit SHA
        id: commit
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  build:
    needs: checkout
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ format('{0}-NTSYNC-{1}', needs.checkout.outputs.version, needs.checkout.outputs.commitid) }}
